# Generated by Django 4.2.3 on 2023-08-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListOfAllModel",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("class_id", models.IntegerField()),
                ("class_name", models.CharField(max_length=16, verbose_name="类名称")),
                ("info", models.CharField(max_length=16, verbose_name="简介")),
                ("effect_id", models.IntegerField()),
                ("effect_name", models.CharField(max_length=16, verbose_name="效果")),
            ],
        ),
    ]
