# Generated by Django 4.2.3 on 2023-08-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_listofallmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassOfIngredients",
            fields=[
                ("class_id", models.IntegerField(primary_key=True, serialize=False)),
                ("class_name", models.CharField(max_length=16, verbose_name="类名称")),
                ("name_cn", models.CharField(max_length=16, verbose_name="cn类名称")),
            ],
        ),
        migrations.AddField(
            model_name="listofallmodel",
            name="img",
            field=models.ImageField(
                blank="True", null=True, upload_to="img/", verbose_name="图鉴图片"
            ),
        ),
        migrations.AddField(
            model_name="listofallmodel",
            name="img_detail",
            field=models.ImageField(
                blank="True", null=True, upload_to="img/", verbose_name="图鉴细节图片"
            ),
        ),
    ]
