# Generated by Django 4.2.3 on 2023-08-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_classofingredients_listofallmodel_img_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("dish_id", models.IntegerField(primary_key=True, serialize=False)),
                ("dish_name", models.CharField(max_length=16, verbose_name="食谱名称")),
                ("name_cn", models.CharField(max_length=16, verbose_name="cn名称")),
                ("ingreOne_class_id", models.IntegerField()),
                ("ingreOne_id", models.IntegerField()),
                ("ingreTwo_class_id", models.IntegerField()),
                ("ingreTwo_id", models.IntegerField()),
                ("ingreThree_class_id", models.IntegerField()),
                ("ingreThree_id", models.IntegerField()),
                ("ingreFour_class_id", models.IntegerField()),
                ("ingreFour_id", models.IntegerField()),
                ("FuzzClassQuery", models.BooleanField(default=False)),
                ("dish_info", models.CharField(max_length=32, verbose_name="简介")),
            ],
        ),
        migrations.AlterField(
            model_name="listofallmodel",
            name="info",
            field=models.CharField(max_length=32, verbose_name="简介"),
        ),
    ]
