# Generated by Django 4.2.3 on 2023-08-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_listofeffect_rename_id_listofclass_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listofeffect",
            name="effect_id",
            field=models.IntegerField(
                auto_created=True, default=0, primary_key=True, serialize=False
            ),
        ),
    ]
