# Generated by Django 4.2.3 on 2023-08-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_listofeffect_effect_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listofall",
            name="effect_name",
        ),
        migrations.AlterField(
            model_name="listofall",
            name="effect_id",
            field=models.IntegerField(default=10),
        ),
    ]
