# Generated by Django 4.2.3 on 2023-08-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_listofall_effect_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listofall",
            name="item_name",
            field=models.CharField(max_length=16, verbose_name="名称"),
        ),
    ]
