# Generated by Django 4.2.3 on 2023-08-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_listofall_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingreFour_class_id",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingreFour_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingreOne_class_id",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingreOne_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingreThree_class_id",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingreThree_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingreTwo_class_id",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingreTwo_id",
            field=models.IntegerField(default=0),
        ),
    ]
