# Generated by Django 4.2.3 on 2023-08-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_recipe_ingrefour_class_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingreFour_class_id",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingreOne_class_id",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingreThree_class_id",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingreTwo_class_id",
        ),
    ]
