# Generated by Django 4.2.3 on 2023-08-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_recipe_ingrefour_class_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingreFour_class_id",
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingreOne_class_id",
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingreThree_class_id",
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingreTwo_class_id",
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="FuzzClassQuery",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="dish_info",
            field=models.CharField(max_length=32, null=True, verbose_name="简介"),
        ),
    ]
