# Generated by Django 4.2.3 on 2023-08-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_material_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="PouchGetType",
            field=models.CharField(max_length=16),
        ),
    ]
