# Generated by Django 4.2.3 on 2023-08-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_material_hitpointrecover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="CureEffectType",
            field=models.CharField(max_length=32, verbose_name="功效"),
        ),
    ]
