# Generated by Django 4.2.3 on 2023-08-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_material_cureeffecttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="DyeColor",
            field=models.CharField(max_length=32, verbose_name="染色"),
        ),
        migrations.AlterField(
            model_name="material",
            name="PouchCategory",
            field=models.CharField(max_length=32, verbose_name="种类"),
        ),
        migrations.AlterField(
            model_name="material",
            name="PouchSpecialDeal",
            field=models.CharField(max_length=32, verbose_name="特殊作用"),
        ),
        migrations.AlterField(
            model_name="material",
            name="PouchUseType",
            field=models.CharField(max_length=32, verbose_name="用途"),
        ),
    ]
