# Generated by Django 4.2.3 on 2023-08-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_material_dyecolor_alter_material_pouchcategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="FuzzClassQuery",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="dish_name",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingreFour_class_id",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingreFour_id",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingreOne_class_id",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingreOne_id",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingreThree_class_id",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingreThree_id",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingreTwo_class_id",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingreTwo_id",
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingre1",
            field=models.CharField(max_length=32, null=True, verbose_name="原料1"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingre2",
            field=models.CharField(max_length=32, null=True, verbose_name="原料2"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingre3",
            field=models.CharField(max_length=32, null=True, verbose_name="原料3"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingre4",
            field=models.CharField(max_length=32, null=True, verbose_name="原料4"),
        ),
    ]
