# Generated by Django 4.2.3 on 2023-08-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_recipe_dish_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="dish_info",
            field=models.CharField(max_length=1024, null=True, verbose_name="简介"),
        ),
    ]
