# Generated by Django 4.2.3 on 2023-08-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_recipe_dish_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="dish_id",
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
