# Generated by Django 4.2.3 on 2023-09-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_delete_listofall_remove_class_name_class_effect_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="class_name",
            field=models.CharField(default="", max_length=16, verbose_name="类名称"),
        ),
    ]
