# Generated by Django 4.2.3 on 2023-09-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_material_class_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="dish_info_en",
            field=models.CharField(max_length=1024, null=True, verbose_name="en简介"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="name_en",
            field=models.CharField(default="", max_length=16, verbose_name="en名称"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="para",
            field=models.CharField(default="", max_length=8, verbose_name="加成"),
        ),
    ]
