# Generated by Django 4.2.3 on 2023-09-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_recipe_dish_info_en_recipe_name_en_recipe_para"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="para",
            field=models.CharField(default="", max_length=32, verbose_name="加成"),
        ),
    ]
