# Generated by Django 4.2.3 on 2023-09-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_alter_recipe_para"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="name_en",
            field=models.CharField(default="", max_length=64, verbose_name="en名称"),
        ),
    ]
