# Generated by Django 4.2.3 on 2023-09-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_alter_recipe_name_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="img_path",
            field=models.CharField(default="", max_length=64, verbose_name="img路径"),
        ),
    ]
